package me.exnfachjan.twitchRandomizer.data;

import org.bukkit.Bukkit;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.zip.CRC32;

/**
 * Single-file session store. All runtime data (timer, queue, locales, session
 * state, dragon-kill stats) lives in data.yml so the plugin folder stays tidy.
 * A CRC32 checksum field lets the plugin detect manual edits and log a warning.
 */
public class DataStore {

    private static final String FILE_NAME  = "data.yml";
    private static final String HEADER     = "# AUTO-GENERATED by TwitchRandomizer – DO NOT EDIT MANUALLY\n";
    private static final String CHKSUM_KEY = "__checksum";

    private final JavaPlugin plugin;
    private final File       file;
    private final YamlConfiguration yaml;

    public DataStore(JavaPlugin plugin) {
        this.plugin = plugin;
        this.file   = new File(plugin.getDataFolder(), FILE_NAME);
        this.yaml   = file.exists()
                ? YamlConfiguration.loadConfiguration(file)
                : new YamlConfiguration();
        if (file.exists()) verifyChecksum();
        migrateOldFiles();
    }

    // ── I/O ──────────────────────────────────────────────────────────────────

    public synchronized void save() {
        try {
            plugin.getDataFolder().mkdirs();
            // Compute checksum over content without the checksum field itself
            yaml.set(CHKSUM_KEY, null);
            String body = yaml.saveToString();
            yaml.set(CHKSUM_KEY, crc32(body));
            try (Writer w = new OutputStreamWriter(new FileOutputStream(file), StandardCharsets.UTF_8)) {
                w.write(HEADER);
                w.write(yaml.saveToString());
            }
        } catch (IOException e) {
            plugin.getLogger().warning("[DataStore] Save failed: " + e.getMessage());
        }
    }

    public void saveAsync() {
        try {
            Bukkit.getScheduler().runTaskAsynchronously(plugin, this::save);
        } catch (Throwable t) {
            save(); // fallback during early startup
        }
    }

    private void verifyChecksum() {
        if (!yaml.contains(CHKSUM_KEY)) return;
        long stored = yaml.getLong(CHKSUM_KEY);
        yaml.set(CHKSUM_KEY, null);
        long expected = crc32(yaml.saveToString());
        if (stored != expected) {
            plugin.getLogger().warning(
                "[DataStore] data.yml was manually modified (checksum mismatch). " +
                "Loaded values may be inconsistent.");
        }
        yaml.set(CHKSUM_KEY, stored);
    }

    private static long crc32(String s) {
        CRC32 crc = new CRC32();
        crc.update(s.getBytes(StandardCharsets.UTF_8));
        return crc.getValue();
    }

    // ── Timer ─────────────────────────────────────────────────────────────────

    public synchronized long getTimerElapsed() {
        return yaml.getLong("timer.elapsed_seconds", 0L);
    }

    public synchronized void setTimerState(long elapsed, boolean running) {
        yaml.set("timer.elapsed_seconds", elapsed);
        yaml.set("timer.running", running);
        save();
    }

    // ── Queue ─────────────────────────────────────────────────────────────────

    public synchronized List<String> getQueue() {
        return yaml.getStringList("queue");
    }

    public synchronized void setQueue(List<String> queue) {
        yaml.set("queue", new ArrayList<>(queue));
    }

    // ── Player locales ────────────────────────────────────────────────────────

    public synchronized Map<UUID, String> getPlayerLocales() {
        Map<UUID, String> result = new HashMap<>();
        ConfigurationSection sec = yaml.getConfigurationSection("player_locales");
        if (sec == null) return result;
        for (String key : sec.getKeys(false)) {
            try { result.put(UUID.fromString(key), sec.getString(key)); }
            catch (IllegalArgumentException ignored) {}
        }
        return result;
    }

    public synchronized void setPlayerLocales(Map<UUID, String> locales) {
        yaml.set("player_locales", null);
        for (Map.Entry<UUID, String> e : locales.entrySet()) {
            yaml.set("player_locales." + e.getKey(), e.getValue());
        }
    }

    // ── Session (for SessionConfig) ───────────────────────────────────────────

    public synchronized boolean getSessionBoolean(String path, boolean def) {
        return yaml.getBoolean("session." + path, def);
    }

    public synchronized String getSessionString(String path, String def) {
        String v = yaml.getString("session." + path);
        return v != null ? v : def;
    }

    public synchronized void setSession(String path, Object value) {
        yaml.set("session." + path, value);
    }

    public synchronized void clearSession() {
        yaml.set("session", null);
    }

    // ── Dragon-kill run stats ─────────────────────────────────────────────────

    public synchronized void setRunData(String path, Object value) {
        yaml.set("runs." + path, value);
    }

    // ── Migration from old individual files ───────────────────────────────────

    private void migrateOldFiles() {
        File dir = plugin.getDataFolder();
        if (!dir.exists()) return;
        boolean any = false;

        // timer.yml → timer.*
        File oldTimer = new File(dir, "timer.yml");
        if (oldTimer.exists()) {
            YamlConfiguration c = YamlConfiguration.loadConfiguration(oldTimer);
            yaml.set("timer.elapsed_seconds", c.getLong("elapsedSeconds", 0L));
            yaml.set("timer.running", false);
            oldTimer.delete();
            any = true;
            plugin.getLogger().info("[DataStore] Migrated timer.yml → data.yml");
        }

        // queue.txt → queue
        File oldQueue = new File(dir, "queue.txt");
        if (oldQueue.exists()) {
            List<String> lines = new ArrayList<>();
            try (BufferedReader br = new BufferedReader(
                    new InputStreamReader(new FileInputStream(oldQueue), StandardCharsets.UTF_8))) {
                String line;
                while ((line = br.readLine()) != null) {
                    line = line.trim();
                    if (!line.isEmpty()) lines.add(line);
                }
            } catch (IOException e) {
                plugin.getLogger().warning("[DataStore] Could not migrate queue.txt: " + e.getMessage());
            }
            yaml.set("queue", lines);
            oldQueue.delete();
            any = true;
            plugin.getLogger().info("[DataStore] Migrated queue.txt → data.yml");
        }

        // player_locales.yml → player_locales.*
        File oldLocales = new File(dir, "player_locales.yml");
        if (oldLocales.exists()) {
            YamlConfiguration c = YamlConfiguration.loadConfiguration(oldLocales);
            yaml.set("player_locales", null);
            for (String key : c.getKeys(false)) {
                yaml.set("player_locales." + key, c.getString(key));
            }
            oldLocales.delete();
            any = true;
            plugin.getLogger().info("[DataStore] Migrated player_locales.yml → data.yml");
        }

        // session.yml → session.*
        File oldSession = new File(dir, "session.yml");
        if (oldSession.exists()) {
            YamlConfiguration c = YamlConfiguration.loadConfiguration(oldSession);
            for (String key : c.getKeys(true)) {
                if (!c.isConfigurationSection(key)) {
                    yaml.set("session." + key, c.get(key));
                }
            }
            oldSession.delete();
            any = true;
            plugin.getLogger().info("[DataStore] Migrated session.yml → data.yml");
        }

        // stats.yml → runs.*
        File oldStats = new File(dir, "stats.yml");
        if (oldStats.exists()) {
            YamlConfiguration c = YamlConfiguration.loadConfiguration(oldStats);
            for (String key : c.getKeys(true)) {
                if (!c.isConfigurationSection(key)) {
                    yaml.set("runs." + key, c.get(key));
                }
            }
            oldStats.delete();
            any = true;
            plugin.getLogger().info("[DataStore] Migrated stats.yml → data.yml");
        }

        if (any) {
            save();
            plugin.getLogger().info("[DataStore] Migration complete → data.yml");
        }
    }
}
